export const SITE_CONFIG = {
  name: "4Chaos",
  title: "4Chaos",
  description: "Join the best PvP server 4Chaos. Play, compete, and connect with thousands of players worldwide.",
  url: "https://4chaos.com",
  domain: "4chaos.com",
  keywords: [
    "4chaos",
    "4story",
    "4story privateserver", 
    "mmorpg",
    "online game",
    "community",
    "gaming server",
    "multiplayer",
    "rpg",
    "aion online",
    "gameforge",
    "metin2",
  ] as string[],
  authors: [{ name: "4Chaos Team" }] as { name: string }[],
  creator: "4Chaos Team",
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "4Chaos",
    image: {
      url: "/images/4Chaos.png",
      width: 1200,
      height: 630,
      alt: "4Chaos Official Logo",
    },
  },
  twitter: {
    card: "summary_large_image",
    creator: "@4chaos",
    image: "/images/4Chaos.png",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};
