#!/usr/bin/env node

/**
 * Script pour activer/désactiver le mode maintenance
 * Usage: node scripts/maintenance.js [on|off|status]
 */

const fs = require('fs');
const path = require('path');

const ENV_FILE = path.join(__dirname, '..', '.env.local');
const MAINTENANCE_KEY = 'NEXT_PUBLIC_MAINTENANCE_MODE';

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) {
    return {};
  }
  
  const content = fs.readFileSync(ENV_FILE, 'utf-8');
  const env = {};
  
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        env[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
  
  return env;
}

function writeEnvFile(env) {
  const lines = [
    '# Environment Variables',
    '# Generated by maintenance script',
    '',
  ];
  
  Object.entries(env).forEach(([key, value]) => {
    lines.push(`${key}=${value}`);
  });
  
  fs.writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
}

function getMaintenanceStatus() {
  const env = readEnvFile();
  return env[MAINTENANCE_KEY] === 'true';
}

function setMaintenanceMode(enabled) {
  const env = readEnvFile();
  env[MAINTENANCE_KEY] = enabled ? 'true' : 'false';
  
  // Ensure API URL is set
  if (!env.NEXT_PUBLIC_API_URL) {
    env.NEXT_PUBLIC_API_URL = 'http://localhost:8080/api';
  }
  
  writeEnvFile(env);
}

function showStatus() {
  const isEnabled = getMaintenanceStatus();
  console.log('\n🔧 Mode Maintenance Status:');
  console.log(`   ${isEnabled ? '🔴 ACTIVÉ' : '🟢 DÉSACTIVÉ'}`);
  console.log('');
  
  if (isEnabled) {
    console.log('   Le site affiche la page de maintenance.');
    console.log('   Pour désactiver: node scripts/maintenance.js off');
  } else {
    console.log('   Le site fonctionne normalement.');
    console.log('   Pour activer: node scripts/maintenance.js on');
  }
  console.log('');
}

function main() {
  const command = process.argv[2];
  
  switch (command) {
    case 'on':
      setMaintenanceMode(true);
      console.log('\n✅ Mode maintenance ACTIVÉ');
      console.log('   Le site affichera la page de maintenance.');
      console.log('   Redémarrez le serveur de développement si nécessaire.\n');
      break;
      
    case 'off':
      setMaintenanceMode(false);
      console.log('\n✅ Mode maintenance DÉSACTIVÉ');
      console.log('   Le site fonctionne normalement.');
      console.log('   Redémarrez le serveur de développement si nécessaire.\n');
      break;
      
    case 'status':
      showStatus();
      break;
      
    default:
      console.log('\n🔧 Script de gestion du mode maintenance\n');
      console.log('Usage:');
      console.log('  node scripts/maintenance.js on      - Activer la maintenance');
      console.log('  node scripts/maintenance.js off     - Désactiver la maintenance');
      console.log('  node scripts/maintenance.js status  - Voir le statut actuel');
      console.log('');
      showStatus();
  }
}

main();
